on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
- uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - run: clasp push
    - run: clasp deploy

  